//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeSpecialization
    {
        public int Id { get; set; }
        public int CollegeId { get; set; }
        public string SpecializationCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> BudgetSeatsCount { get; set; }
        public Nullable<int> PaidSeatsCount { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public int FormOfEducatingId { get; set; }
        public bool IsEntranceTest { get; set; }
        public Nullable<double> PassingScore { get; set; }
    
        public virtual College College { get; set; }
        public virtual FormOfEducation FormOfEducation { get; set; }
        public virtual SpecializationInfo SpecializationInfo { get; set; }
    }
}
