//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dormitory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dormitory()
        {
            this.DormitoryMedias = new HashSet<DormitoryMedia>();
        }
    
        public int Id { get; set; }
        public int InstitutionId { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    
        public virtual EducationalInstitution EducationalInstitution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DormitoryMedia> DormitoryMedias { get; set; }
    }
}
