//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailState
    {
        public string UserLogin { get; set; }
        public int VerificationCode { get; set; }
        public System.DateTime DateSentCode { get; set; }
        public bool IsVerificated { get; set; }
    
        public virtual User User { get; set; }
    }
}
