//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Feedback()
        {
            this.FeedbackMedias = new HashSet<FeedbackMedia>();
        }
    
        public int Id { get; set; }
        public string UserLogin { get; set; }
        public int EducationalInstitutionId { get; set; }
        public string Title { get; set; }
        public string FeedbackText { get; set; }
        public int CountLikes { get; set; }
    
        public virtual EducationalInstitution EducationalInstitution { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedbackMedia> FeedbackMedias { get; set; }
        public virtual FeedbackStatsForm FeedbackStatsForm { get; set; }
    }
}
