//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackMedia
    {
        public int Id { get; set; }
        public int FeedbackId { get; set; }
        public int MediaId { get; set; }
    
        public virtual Feedback Feedback { get; set; }
        public virtual MediaFile MediaFile { get; set; }
    }
}
