//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackStatsForm
    {
        public int FeedbackId { get; set; }
        public Nullable<double> TotalMark { get; set; }
        public Nullable<double> TeachersMark { get; set; }
        public Nullable<double> TechnologiesMark { get; set; }
        public Nullable<double> ComfortMark { get; set; }
        public Nullable<double> DecorMark { get; set; }
    
        public virtual Feedback Feedback { get; set; }
    }
}
